### ISSUE TITLE
Please respond to me.

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#12]
I have been working on the project for a while now and I have tried many things over. I think we need to meet or at least talk over github so that we can pool ideas.

**Comment by cthan004** [comment]
Sry man was doing another class hmwk since the TA moved the due date.

**Comment by cthan004** [comment]
And yea I was trying to figure out how to do recursion on thread_get_priority.
donorList is to store the donors for each threads. I followed the TA instruction on this one.
Not sure if sema->wait works
