### ISSUE TITLE
All tests done except priority-condvar

### ISSUE THREAD

**Issue by cthan004** [cthan004/pintos#15]
I managed to pass all alarm and priority tests except priority-condvar w/ the new and improve get_priority :D.

Seems like we have to do some priority stuff in cond_signal() in synch.c.
There's a hint by TA in piazza. It's late so im gonna sleep.

**Comment by oribix** [comment]
Thats awesome new!

**Comment by oribix** [comment]
News*

**Comment by oribix** [comment]
btw did I mention you are a beast?
