### ISSUE TITLE
We need to replace the "turn off interupts" with locks and semaphores

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#17]
we need to try to get rid of as much interrupt disabling as possible.

**Comment by oribix** [comment]
we could make a test-and-set function to replace all the disable-enable interrupt clauses

**Comment by cthan004** [comment]
I agree.
But I dont think we can use locks and semaphores in Lock_acquire/release (cant acquire again in acquire).
Im also sure that we need to disable interrupts in set_priority.
However I already test most functions (acquire/release/set_priority) with "interrupts on" and still pass the tests so Im not sure if we should turn off or not...

**Comment by oribix** [comment]
probably best to do that at a later time. We gotta get priority-condvar before the end of today. I have been trying at it but i keep page faulting.
