### ISSUE TITLE
All Alarm and Priority tests done!!!

### ISSUE THREAD

**Issue by cthan004** [cthan004/pintos#18]
I managed to get all tests done.
Try testing and see if it pass on ur computer.
If it pass, you can submit it :).

**Comment by cthan004** [comment]
Let me know the result when you test/submit it. thx

**Comment by oribix** [comment]
alright im trying it now

**Comment by oribix** [comment]
dude you're a beast. Everything is good. How did you figure it out? I spent a long time just hacking at at and couldnt do anything.

**Comment by oribix** [comment]
we can turn in

**Comment by oribix** [comment]
I submitted.

**Comment by cthan004** [comment]
Haha I just follow TA advice on piazza.

**Comment by oribix** [comment]
I never thought about going to piazza....

**Comment by oribix** [comment]
RIP me
