### ISSUE TITLE
I have created a few useful tags and branches for the next project.

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#19]
Im still reading up on the project but I have created a few useful branches and tags. My current branches and tags are as follows:

branches:
master
threads
userprog

tags:
blankslate
Project1

make these branches in your repository and pull them from mine. We might need to use blankslate in the future (its a fresh copy of pintos. Dont mess with it. mess with userprog instead). When you make these branches and tags, make sure that they have ONLY THE FIRST COMMIT on them otherwise you might not preserve their integrity when you pull from my repository.

you can do this easily by running the following terminal commands:

git checkout 3f2ef523a2d0a9f65eb13fa42477e23bfa963aa9
git branch userprog
git branch threads
git tag blankslate
git tag Project1
git push origin userprog
git push origin threads
git push origin blankslate
git push origin Project1

From there you should be able to do a pull request on github to bring them up to speed. The checkout command should checkout the original upload of Pintos.

Note: only do work in the userprog branch. We don't want to mix our new code with the master branch.

**Comment by cthan004** [comment]
Alright
