### ISSUE TITLE
Project 1 grade 30/56?

### ISSUE THREAD

**Issue by cthan004** [cthan004/pintos#30]
Did you get 30/56 too?

**Comment by cthan004** [comment]
These are the tests we fail according to the TA...

Functionality of priority scheduler (tests/threads/Rubric.priority):
             3/ 3 tests/threads/priority-change
             3/ 3 tests/threads/priority-preempt

```
         3/ 3 tests/threads/priority-fifo
         3/ 3 tests/threads/priority-sema
      ** 0/ 3 tests/threads/priority-condvar

      ** 0/ 3 tests/threads/priority-donate-one
      ** 0/ 3 tests/threads/priority-donate-multiple
      ** 0/ 3 tests/threads/priority-donate-multiple2
      ** 0/ 3 tests/threads/priority-donate-nest
      ** 0/ 5 tests/threads/priority-donate-chain
      ** 0/ 3 tests/threads/priority-donate-sema
      ** 0/ 3 tests/threads/priority-donate-lower
```

**Comment by oribix** [comment]
i got 0/56 as well

**Comment by cthan004** [comment]
I believed we passed all the test cases...

**Comment by cthan004** [comment]
Can you download the tar files you submit and make check it again to see if it passed the tests?
Send it to me so I can check it on my laptop too.

**Comment by cthan004** [comment]
Also, how many submissions did you make?

**Comment by oribix** [comment]
I made 2. I think he may have graded the first or something. That one had like half the tests missing. We can talk to him on wednessday.
