### ISSUE TITLE
We need to meet up to work on Project 2

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#31]
We have been lazy on adding to Project 2. I do remember that you attend the later lab session but please, if there are no time conflicts, come to the session in the morning. I cant attend the later session because I a have classes overlapping it. It sucks that our comminucation is lacking and I'd really prefer that we stick together so that we can have two heads thinking at the same time.

I want to meet up as much as possilble during this week so that we can code together.

I'm very restricted Wednessday so that is why I need you to come in the morning, otherwise we cant meet any other time on that day.

I am free pretty much any time on monday and any time Friday. Im am virtually unrestricted on Tuesday and thursday but I have midterms on those days. I have to prepare for them but depending on what times you give me, I will manage.

Here is my schedule:
INTRO TO EMBEDDED SYSTEMS
CS -120B-001        4.00    TR  0510PM-0630PM   BRNHL   B118

LABORATORY
CS -120B-021      NG    0.00    M   0810AM-1100AM   CHUNG   136

AUTOMATA AND FORMAL LANGUAGES
CS -150 -001        4.00    TR  1110AM-1230PM   CHUNG   142
            W   0510PM-0600PM   MSE     103

DESIGN OF OPERATING SYSTEMS
CS -153 -001        4.00    MWF     0310PM-0400PM   BRNHL   A125

LABORATORY
CS -153 -021      NG    0.00    W   0810AM-1100AM   CHUNG   133

GENERAL PHYSICS
PHYS-040C-001       5.00    TR  0940AM-1100AM   PHY     2000

DISCUSSION
PHYS-040C-006     NG    0.00    F   1110AM-1200PM   CHUNG   143

LABORATORY
PHYS-040C-109     NG    0.00    W   1210PM-0300PM   PHY     2029 

I don't know how busy you are, but try to find some any space where we can meet. We can work in the ACM club room at WCH 226.

Please reply with all the times that don't conflict after you consider your plans for the week. Im going to be at UCR as long as possible every day so don't be scared to give me a super late time or super early one.

**Comment by cthan004** [comment]
I am free on Wednesday after 4 and Friday between 2-3 and after 5.
I am also free on Thursday, but you should focus on your midterm.
Don't worry much, I am sure we can finish on time.

And I will go to lab this week.

**Comment by oribix** [comment]
My midterm is from 11-1230 on thursday. Im free after that. lets meet up at WCH 226 at those times.

**Comment by cthan004** [comment]
Hey Im gonna be a bit late. Sry.
