### ISSUE TITLE
Do you think we need to burn slack days?

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#39]
I dont think we can finish in time. I need to ask you because I also have physics hw to do. if we are going to burn slack days, I'd rather use the rest of today working on physics. Until you respond, I'll be working on physics.

**Comment by cthan004** [comment]
Yea lets burn slack days

**Comment by oribix** [comment]
This probably wasn't even a real question XD. I'm going to wake up early tomorrow. Im really going to go hard on the coding.
