### ISSUE TITLE
I'm going to work on the algorithm for pushing on stack

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#40]
Right now it is spaghetti code and honestly is crap. It will be impossible to figure out what it is doing unless you really sit down for a while. Try to look around for incorrect implementations of concepts. I was never good with concepts and honestly, my greatest strength is in algorithms.

**Comment by cthan004** [comment]
Alright

**Comment by oribix** [comment]
Dont too much about testing yet. Remember that we can't test Until I finish my side, otherwise we will get page faults.
