### ISSUE TITLE
Sorry its been taking me so long.

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#41]
I have been looking through the code and I understand a lot of things now. Give me another half hour and I'll have the code for setup_stack_helper 99% finished.

**Comment by cthan004** [comment]
Take your time.
We have 4 slack days anyway.
I am trying stuff too.

**Comment by oribix** [comment]
Yeah but I want to save at least 2 in the case poop hits the fan and the professor decides to do a project 3

**Comment by cthan004** [comment]
Yea, but this push thing sucks...

Anyway I tried changing CMD_MAX and MAX_ARGS to 128.
This makes it go into load->setup_stack->setup_stack_helper and get a different error.

Also hexdump is kinda useful. You can take a look at what I tried in old userprog.

TA page has this:
Note*: For calculating addresses to push on stack: void *uarg = upage + (karg - (char *) kpage); Where karg is the return value from push, after pushing one of the parsed tokens from the command line. Push uarg onto kpage. Don't forget to reverse the order of the addresses.
I tried but it didnt work when I hexdump.

Hope this help

**Comment by oribix** [comment]
My dad is going to need help to set up for a party (he is a DJ). I am going to be gone at 7.

**Comment by oribix** [comment]
In the mean time, I have pushed my work. It is extremely close to the correct algorithm but the post you just made tells me that I skrewed up pushing the addresses. I'll use your tip right now to try to fix my code. I only need to change the things that are pushed.

**Comment by oribix** [comment]
ive almost got it
