### ISSUE TITLE
How do you plan to use the child struct?

### ISSUE THREAD

**Issue by oribix** [cthan004/pintos#45]
It was kinda declared with no comments. I can vaguely see how you plan to use it but Im not quite sure how to use it exactly. I can;t find a way to get the cid from the cElem alone.

**Comment by cthan004** [comment]
I think we can get thread from cid by check through all_list.
wait is a bool that becomes true when we call process_wait the first time So if we call process_wait on the same child, we can simply exit function.

But feel free to add anything if its gonna make getting thread easier.

**Comment by oribix** [comment]
sure thing. Its been a while since I had used that function fo I forgot  about it :<
