### ISSUE TITLE
Project two 75/76 passed

### ISSUE THREAD

**Issue by cthan004** [cthan004/pintos#50]
I couldn't sleep so I did some more work on it. Turns out the TA codes work. Never doubt his codes.

The last test seems difficult. I think we have to be careful when call palloc_get and palloc_free. Probably have to move some codes around.

I already tar and turned in a copy with 75/76 tests passed. I think you should pull/test/submit another copy too just in case.

I'm going to LA tmr and won't get a chance to work on it till tuesday morning.
(I was not gonna go if we didnt finish)

Anyway you can try to pass the last test, but im already satisfy.

**Comment by cthan004** [comment]
Also the code is really messy with unused variables and stuffs and there are warnings (it compiles though).

**Comment by oribix** [comment]
seriously wtf man. At least let me learn lol

**Comment by oribix** [comment]
I'll look at the last test after I do my 120b work. Probably not worth it though since we would have to burn another flex day (unless you already burned it)

**Comment by cthan004** [comment]
I have not burn it. But yea I also think its not worth it.

**Comment by oribix** [comment]
I wonder If I should go through and clean the code so that the TA can read it better. I might put a disclaimer saying that it is functionally the same. I'll ask on piazza.

**Comment by oribix** [comment]
I posted the question. The TA said that it was ok that the code looks bad. If we pass all the tests, he won't look at it anyways.
