### ISSUE TITLE
Turning it in

### ISSUE THREAD

**Issue by cthan004** [cthan004/pintos#7]
Do you want to add anything else?

**Comment by oribix** [comment]
i cant think of anything

**Comment by oribix** [comment]
it looks done but i think that we should check for errors in spelling

**Comment by cthan004** [comment]
alright

**Comment by oribix** [comment]
i'll turn in in a preliminary copy. I dont want something unfortuante to happen. We only need to turn in one copy

**Comment by cthan004** [comment]
cool.
And I dont see any spelling errors

**Comment by oribix** [comment]
grammarcheck.me

**Comment by oribix** [comment]
only two spelling mistakes

**Comment by cthan004** [comment]
all good?

**Comment by oribix** [comment]
im giving it to you

**Comment by cthan004** [comment]
Did u turn it in?

**Comment by oribix** [comment]
i turned in a preliminary one to be safe. the one with the two spelling fixes was late but the preliminary one was OK

**Comment by oribix** [comment]
the preliminary was turned in at 11:50. the two spelling fixes were turned in at 11:59

**Comment by cthan004** [comment]
alright cool
